import {EventEmitter, Injectable} from '@angular/core';
import {LangCode} from '../common/common-interfaces';

const sen_en: { [p: string]: string } = {
    undo: 'Undo',
    redo: 'Redo',
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    strikethrough: 'Strikethrough',
    subscript: 'Subscript',
    superscript: 'Superscript',
    justifyLeft: 'Justify Left',
    justifyCenter: 'Justify Center',
    justifyRight: 'Justify Right',
    justifyFull: 'Justify Full',
    indent: 'Indent',
    outdent: 'Outdent',
    unorderedList: 'Unordered List',
    orderedList: 'Ordered List',
    insertLink: 'Insert Link',
    unlink: 'Unlink',
    insertImage: 'Insert Image',
    insertFtp: 'Insert File/Image from FTP',
    insertVideo: 'Insert Video',
    horizontalLine: 'Horizontal Line',
    insertTable: 'Insert Table',
    clearFormatting: 'Clear Formatting',
    HTMLCode: 'HTML Code',
    textColor: 'Text Color',
    backgroundColor: 'Background Color',
    placeholder: 'Enter text here...',
    notice: 'Notice',
    pasteDisabled: 'Pasting from clipboard is disallowed.',
    cancel: 'Cancel',
    numRows: 'Number of rows',
    numCols: 'Number of columns',
    stroke: 'Stroke',
    insertLinkPlaceholder: '"https://www.boo.com" or "/c/fashion"',
    insertLinkUrlTitle: 'Link URL',
    insertLinkValidatorRequired: 'You must enter a value.',
    insertLinkValidatorPattern: 'Invalid URL format.',
    insertVideoValidatorRequired: 'You must enter video URL.',
    insertVideoValidatorPattern: 'Video URL has a bad format.',
    insertVideoUrlLabel: 'Enter Video Url',
    insertVideoUseOrigSize: 'Use original thumbnail size',
    insertVideoUseManualSize: 'Use given size',
    width: 'Width',
    height: 'Height',
    keepRatio: 'Keep original image aspect ratio',
    crop: 'Crop',
    alt: 'Alt',
    title: 'Title',
    editImageDialogTitle: 'Image Properties',
    editTableDialogTitle: 'Edit Table',
    insertColorDialogTitle: 'Set Color',
    insertVideoDialogTitle: 'Insert Video',
    fullWidth: '100% width',
    tableActions: 'Table actions',
    addRowBellow: 'Add Row Bellow',
    addRowUp: 'Add Row Up',
    addColumnRight: 'Add Column Right',
    addColumnLeft: 'Add Column Left',
    deleteColumn: 'Delete Column',
    deleteRow: 'Delete Row',
    deleteTable: 'Delete Table',
    setColumnWidths: 'Set Column Widths',
    h1: 'Heading 1',
    h2: 'Heading 2',
    h3: 'Heading 3',
    h4: 'Heading 4',
    h5: 'Heading 5',
    h6: 'Heading 6',
    p: 'Paragraph',
    clear: 'Default',
    imageActions: 'Image Actions',
    insertImageUrl: 'Set Link',
    deleteImage: 'Delete Image',
    openInNewWindow: 'Open in new window',
    presetColors: 'Preset colors',
    verticalCellAlignment: 'Vertical cell alignment',
    vAlignTop: 'Top',
    vAlignMiddle: 'Middle',
    vAlignBottom: 'Bottom'
};

const sen_cs: { [p: string]: string } = {
    undo: 'Zpět',
    redo: 'Znovu',
    bold: 'Tučné',
    italic: 'Kurzíva',
    underline: 'Podtržené',
    strikethrough: 'Přeškrtnuté',
    subscript: 'Dolní index',
    superscript: 'Horní index',
    justifyLeft: 'Zarovnat vlevo',
    justifyCenter: 'Zarovnat doprostřed',
    justifyRight: 'Zarovnat vpravo',
    justifyFull: 'Zarovnat do bloku',
    indent: 'Odsazení',
    outdent: 'Zmenšit odsazení',
    unorderedList: 'Nesetříděný seznam',
    orderedList: 'Setříděný seznam',
    insertLink: 'Vložit odkaz',
    unlink: 'Zrušit odkaz',
    insertImage: 'Vložit obrázek',
    insertFtp: 'Vložit soubor/obrázek z FTP',
    insertVideo: 'Vložit video',
    horizontalLine: 'Vodorovná čára',
    insertTable: 'Vložit tabulku',
    clearFormatting: 'Zrušit formátování',
    HTMLCode: 'HTML kód',
    textColor: 'Barva textu',
    backgroundColor: 'Barva pozadí',
    placeholder: 'Sem zadejte text...',
    notice: 'Upozornění',
    pasteDisabled: 'Funkce vkládání ze schránky je zakázána.',
    cancel: 'Zrušit',
    numRows: 'Počet řádků',
    numCols: 'Počet sloupců',
    stroke: 'Ohraničení',
    insertLinkPlaceholder: '"https://www.neco.cz" nebo "/c/moda"',
    insertLinkUrlTitle: 'URL odkazu',
    insertLinkValidatorRequired: 'Musíte zadat hodnotu.',
    insertLinkValidatorPattern: 'Neplatný formát URL.',
    insertVideoValidatorRequired: 'Musíte zadat URL videa.',
    insertVideoValidatorPattern: 'URL videa má nesprávný formát.',
    insertVideoUrlLabel: 'Zadejte Url videa',
    insertVideoUseOrigSize: 'Použít původní velikost náhledu',
    insertVideoUseManualSize: 'Zadat vlastní velikost náhledu',
    width: 'Šířka',
    height: 'Výška',
    keepRatio: 'Zachovat poměr stran originálu',
    crop: 'Ořezat',
    alt: 'Alt',
    title: 'Titulek',
    editImageDialogTitle: 'Vlastnosti obrázku',
    editTableDialogTitle: 'Upravit tabulku',
    insertColorDialogTitle: 'Nastavit barvu',
    insertVideoDialogTitle: 'Vložit video',
    fullWidth: '100% šířka',
    tableActions: 'Akce tabulky',
    addRowBellow: 'Přidat řádek pod',
    addRowUp: 'Přidat řádek nad',
    addColumnRight: 'Přidat sloupec vpravo',
    addColumnLeft: 'Přidat sloupec vlevo',
    deleteColumn: 'Smazat sloupec',
    deleteRow: 'Smazat řádek',
    deleteTable: 'Smazat tabulku',
    setColumnWidths: 'Nastavit šířky sloupců',
    h1: 'Nadpis 1',
    h2: 'Nadpis 2',
    h3: 'Nadpis 3',
    h4: 'Nadpis 4',
    h5: 'Nadpis 5',
    h6: 'Nadpis 6',
    p: 'Odstavec',
    clear: 'Výchozí',
    imageActions: 'Akce obrázku',
    deleteImage: 'Smazat obrázek',
    insertImageUrl: 'Nastavit odkaz',
    openInNewWindow: 'Otevřít v novém okně',
    presetColors: 'Přednastavené barvy',
    verticalCellAlignment: 'Svislé zarovnání buněk',
    vAlignTop: 'Nahoru',
    vAlignMiddle: 'Doprostřed',
    vAlignBottom: 'Dolů'
};

const sen_sk: { [p: string]: string } = {
    undo: 'Späť',
    redo: 'Znovu',
    bold: 'Tučné',
    italic: 'Kurzíva',
    underline: 'Podčiarknuté',
    strikethrough: 'Prečiarknuté',
    subscript: 'Dolný index',
    superscript: 'Horný index',
    justifyLeft: 'Zarovnať vľavo',
    justifyCenter: 'Zarovnať do stredu',
    justifyRight: 'Zarovnať vpravo',
    justifyFull: 'Zarovnať do bloku',
    indent: 'Odsadenie',
    outdent: 'Zmenšiť odsadenie',
    unorderedList: 'Nezotriedený zoznam',
    orderedList: 'Zotriedený zoznam',
    insertLink: 'Vložiť odkaz',
    unlink: 'Zrušiť odkaz',
    insertImage: 'Vložiť obrázok',
    insertFtp: 'Vložiť súbor/obrázok z FTP',
    insertVideo: 'Vložiť video',
    horizontalLine: 'Vodorovná čiara',
    insertTable: 'Vložiť tabuľku',
    clearFormatting: 'Zrušiť formátovanie',
    HTMLCode: 'HTML kód',
    textColor: 'Farba textu',
    backgroundColor: 'Farba pozadia',
    placeholder: 'Sem zadajte text...',
    notice: 'Upozornenie',
    pasteDisabled: 'Funkcia vkladania zo schránky je zakázaná.',
    cancel: 'Zrušiť',
    numRows: 'Počet riadkov',
    numCols: 'Počet stĺpcov',
    stroke: 'Ohraničenie',
    insertLinkPlaceholder: '"https://www.neco.cz" alebo "/c/moda"',
    insertLinkUrlTitle: 'URL odkazu',
    insertLinkValidatorRequired: 'Musíte zadať hodnotu.',
    insertLinkValidatorPattern: 'Neplatný formát URL.',
    insertVideoValidatorRequired: 'Musíte zadať URL videa.',
    insertVideoValidatorPattern: 'URL videa má nesprávny formát.',
    insertVideoUrlLabel: 'Zadajte Url videá',
    insertVideoUseOrigSize: 'Použiť pôvodnú veľkosť náhľadu',
    insertVideoUseManualSize: 'Zadať vlastnú veľkosť náhľadu',
    width: 'Šírka',
    height: 'Výška',
    keepRatio: 'Zachovať pomer strán originálu',
    crop: 'Orezať',
    alt: 'Alt',
    title: 'Titulok',
    editImageDialogTitle: 'Vlastnosti obrázku',
    editTableDialogTitle: 'Upraviť tabuľku',
    insertColorDialogTitle: 'Nastaviť farbu',
    insertVideoDialogTitle: 'Vložiť video',
    fullWidth: '100% šírka',
    tableActions: 'Akcia tabuľky',
    addRowBellow: 'Pridať riadok pod',
    addRowUp: 'Pridať riadok nad',
    addColumnRight: 'Pridať stĺpec vpravo',
    addColumnLeft: 'Pridať stĺpec vľavo',
    deleteColumn: 'Zmazať stĺpec',
    deleteRow: 'Zmazať riadok',
    deleteTable: 'Zmazať tabuľku',
    setColumnWidths: 'Nastaviť šírky stĺpcov',
    h1: 'Nadpis 1',
    h2: 'Nadpis 2',
    h3: 'Nadpis 3',
    h4: 'Nadpis 4',
    h5: 'Nadpis 5',
    h6: 'Nadpis 6',
    p: 'Odsek',
    clear: 'Predvolené',
    imageActions: 'Akcia obrázku',
    deleteImage: 'Zmazať obrázok',
    insertImageUrl: 'Nastaviť odkaz',
    openInNewWindow: 'Otvoriť v novom okne',
    presetColors: 'Prednastavené farby',
    verticalCellAlignment: 'Zvislé zarovnanie buniek',
    vAlignTop: 'Hore',
    vAlignMiddle: 'Doprostred',
    vAlignBottom: 'Dole'
};

@Injectable({
    providedIn: 'root'
})
export class LangService {
    set lang(value: LangCode) {
        this.switchLang(value);
    }

    get sen(): { [p: string]: string } {
        return this._sen;
    }

    set sen(value: { [p: string]: string }) {
        this._sen = value;
    }

    private _sen: { [key: string]: string } = {};

    languageChanged: EventEmitter<{ [key: string]: string }> = new EventEmitter<{ [key: string]: string }>();

    constructor() {
        this.switchLang('cs');
    }

    private switchLang(val: LangCode): void {
        switch (val) {
            case 'cs':
                this.sen = sen_cs;
                break;
            case 'en':
                this.sen = sen_en;
                break;
            case 'sk':
                this.sen = sen_sk;
        }
        this.languageChanged.emit(this.sen);
    }
}
